export { PrismaClient, Prisma } from "@prisma/client";
export type {
  Tenant,
  User,
  Manufacturer,
  DeviceCategory,
  Device,
  DeviceDocument,
  Annotation,
  AnnotationEndorsement,
  AnnotationVote,
  AnnotationFlag,
  AnnotationTag,
  AnnotationTagLink,
  Comment,
  CommentVote,
  UserReputation,
  Alert,
  AlertDeviceLink,
  TenantAlertAcknowledgement,
  Sop,
  AuditLog,
  IngestionRun,
} from "@prisma/client";
